dist: trusty
sudo: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
os:
  - linux
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
  - npm install -g @angular/cli
  - npm install -g @angular/compiler
  - npm install -g @angular/compiler-cli
install:
  - npm install
  - cp package.json package.json_
  - npm info . peerDependencies | sed -n 's/^{\{0,1\}[[:space:]]*'\''\{0,1\}\([^:'\'']*\)'\''\{0,1\}:[[:space:]]'\''\([^'\'']*\).*$/\1@\2/p' | xargs npm i
script:
  - ng build
  - rm -rf package.json
  - cp package.json_ package.json
  - npm run packagr
